---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

## Dear Emily, have fun!

```{r}
library(tidyverse)
```

## Simulating your data frame

Skewing toward Conservative votes...

```{r}
sim_rows <- 1000
set.seed(0)
parties <- c("Labour","Conservative","Spont.Other","UKIP","Lib Dem")
# skew it a bit
party_probs <- c(20,200,5,5,1) %>% {./sum(.)}
ids=1:100

df_voters <- tibble(pipd=sample(ids,sim_rows,replace=T),
                    party=sample(parties,sim_rows,replace=T,prob=party_probs)) %>%
  arrange(pipd) %>%
  group_by(pipd) %>%
  mutate(wave=c(letters,LETTERS)[row_number()]) %>%
  ungroup() %>%
  select(pipd,wave,party)
```

```{r,results='as is',echo=F}
knitr::kable(df_voters%>%head(10))
```

## Voting history

The results you want appear in the party_1st, party_2nd, and "flipped" columns.
The nifty trick is the use of base-r's "rle" (run-length encoding). Notice how the history of each voter is stored "horizontally" (list-columns).

```{r}
df_voting_history <- df_voters %>%
  group_by(pipd) %>%
  summarize(party_order=list(rle(party))) %>% # run-length encoding
  mutate(voted_parties=map(party_order,"values"),
         voted_times=map(party_order,"lengths")) %>% # decode rle class
  select(-party_order) %>% # get rid of original rle class
  mutate(party_1st=map_chr(voted_parties,first),
         party_2nd=map_chr(voted_parties,~{if(length(.x)==1) NA else .x[2]}),
         flipped=!is.na(party_2nd),
         parties_voted_for=map_int(voted_parties,length)) %>%
  select(pipd,party_1st,party_2nd,flipped,everything())
```

```{r,results='as is',echo=F}
knitr::kable(df_voting_history%>%head(10))
```

## Hope this helps!
